services:
    - docker:dind

variables:
    DOCKER_HOST: tcp://docket:2375
    DOCKER_DRIVER: overlay2

docker:
    image: docker:stable
    services:
        - docker:dind
    stage: docker
    script:

